### ISSUE TITLE
v0.8 Punchlist

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/docs#112]
There are a few punchlist items that we need to make sure we do not forget:
- We need to add documentation for jsonrpc config for the node, and remove grpc
- We need to update our node tutorials to not use grpc flags, since they are now removed, and also to use jsonrpc flags
- We need to regenerate kwil-cli and kwil-admin reference docs

**Comment by KwilLuke** [comment]
- Update the default chain ID in tutorials and examples.
