### ISSUE TITLE
`--app.http-listen-addr` flag does not exist

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/docs#135]
It seems like we removed `--app.http-listen-addr`. We should update the docs to reflect this, since it is still widely used in tutorials.

**Comment by brennanjl** [comment]
Never mind, it was already deprecated

**Comment by jchappelow** [comment]
I also see mention of port 8080 in a few places, so that should change to 8484 also: https://github.com/search?q=repo%3Akwilteam%2Fdocs+8080&type=code
