### ISSUE TITLE
documentation: kwild binary

### ISSUE THREAD

**Issue by brennanjl** [kwilteam/docs#23]
We will need documentation for the `kwild` binary described here: https://github.com/kwilteam/kwil-db/issues/265

This should include:
- a “quickstart” section, which shows the easiest way to install and run `kwild`.
- a basic example config file that has commonly used variables set.
- an explanation for all configurations.
- an example of a configuration where everything is set.
- documentation on flags (this does not need to cover each config flag, it just needs to show how one can specify configuration).

**Comment by KwilLuke** [comment]
closed in #39
