### ISSUE TITLE
Expired Link in Documentation

### ISSUE THREAD

**Issue by 0xAsten** [kwilteam/docs#77]
The discord link in the following page has expired:

https://github.com/kwilteam/docs/blob/0fdb2a34c931fbb3a55445f1686ade80bb25b915/docs/introduction.md?plain=1#L18

**Comment by brennanjl** [comment]
@0xAsten the link seems to be working for everyone on our team. Can you confirm that the link is still expired for you?

**Comment by 0xAsten** [comment]
> @0xAsten the link seems to be working for everyone on our team. Can you confirm that the link is still expired for you?

Works good for me now. Thank you!
